### ISSUE TITLE
Notificação de PIX não chegou na loja

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-paghiper#11]
Na loja 1125 com id 609954f125f3346073145afb já consta como completed no paghiper e na plataforma nada ainda, vou modificar manualmente para aprovado, como no log não mostra nada, então só avisando para olhar posteriormente algum problema

**Comment by leomp12** [comment]
Não tem sido muito raros os casos de Pix não notificados pelo próprio PagHiper, nesse caso a falha é do lado deles e de fato o pedido não será atualizado, tem alguns tickets abertos da Tia Sônia com o suporte deles (comigo em cópia) sobre isso.
Vou confirmar as notificações, qual é o código da transação?

**Comment by matheusgnreis** [comment]
I6AYGEWLW8WJG2PN

**Comment by leomp12** [comment]
Chegou uma notificação às 14:53 mas com status pendente novamente, eles também fazem isso às vezes:

```
ecomplus-integrations [Mon May 10 2021 14:53:03 GMT-0300 (Brasilia Standard Time)]
Paghiper notification for I6AYGEWLW8WJG2PN
```

Foi ignorada porque não alterava o status do pedido.

**Comment by matheusgnreis** [comment]
Estão meio doido então, porque: 

        "status": "completed",
        "status_date": "2021-05-10 14:50:07",

14:50 mudaram para completado

**Comment by leomp12** [comment]
Sim, a transação no PagHiper fica correta, mas o que eles mandam é um objeto da notificação, com Pix tem acontecido mais ou menos frequente de não vir a notificação como deveria ou vir com status incorreto, às vezes eles até mandam pago e depois mandam pendente.
Mas nesse caso aí vieram duas notificações pendente, não tem erro no app que inclusive registrou ambas, mas como a segunda ainda era de pendente o app não tinha o que fazer.

**Comment by leomp12** [comment]
Mas ela (ou você) pode confirmar com o suporte deles, e chegou mais uma por agora, provavelmente com status pago mas ignorada também porque agora o pedido já está com o mesmo status, segue os horários das notificações:

```
ecomplus-integrations [Mon May 10 2021 12:45:05 GMT-0300 (Brasilia Standard Time)]
Paghiper notification for I6AYGEWLW8WJG2PN
```

```
ecomplus-integrations [Mon May 10 2021 14:53:03 GMT-0300 (Brasilia Standard Time)]
Paghiper notification for I6AYGEWLW8WJG2PN
```

```
ecomplus-integrations [Mon May 10 2021 15:35:20 GMT-0300 (Brasilia Standard Time)]
Paghiper notification for I6AYGEWLW8WJG2PN
```

Só atrasou um bocado...

> Edit.: a última, sendo ignorada sem erro, ou chegou com status pago ou novamente pendente, acredito que foi pago dessa última vez.
