### ISSUE TITLE
Token was valid, but expired

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-paghiper#12]
Trucco reclamou que novamente não veio o status de um pedido cancelado. Fui ver, deu o mesmo problema. No **error**, informa: 

"status":401,"error_code":132,"message":"Token was valid, but expired","user_message":{"en_us":"Invalid login with user ID and access token provided","pt_br":"Login invÃ¡lido com o ID de usuÃ¡rio e token de acesso fornecido"

Fui verificar pelo status 401, só em setembro tem 200 erros com esse status. Abaixo deixei alguns que deram erros, até a 1011 deu. Acredito que esse erro tenha haver com status cancelado. Porque ninguem reclamou com status pendente ou aprovado, somente cancelado. Vi que existem poucas atualizações com esse status.

ecomplus-integrations [Wed Aug 25 2021 09:01:01 GMT-0300 (Brasilia Standard Time)] 
[#1011 / 076B9WKUY7VCDZ21] Unhandled notification: /applications/5fe2591569274c73fcebdf90.json 401

ecomplus-integrations [Fri Aug 27 2021 19:02:57 GMT-0300 (Brasilia Standard Time)] 
[#1227 / 086D9OYG4PQ3BY21] Unhandled notification: /transaction/notification/ 401

ecomplus-integrations [Wed Sep 01 2021 09:01:53 GMT-0300 (Brasilia Standard Time)] 
[#6730 / 08G6ILT6LUYLCQ21] Unhandled notification: /applications/612517cccfbcd9705987feb2.json 401

ecomplus-integrations [Wed Sep 08 2021 08:03:41 GMT-0300 (Brasilia Standard Time)] 
[#1166 / 09AVW7DDJNN2FQ21] Unhandled notification: /applications/602b19db9332dd6865d590fe.json 401

ecomplus-integrations [Wed Sep 08 2021 08:21:21 GMT-0300 (Brasilia Standard Time)] 
[#1483 / 09OTIQ1CY3RXX121] Unhandled notification: /applications/60ddb94aca0b8f794e4ccd8e.json 401

ecomplus-integrations [Wed Sep 01 2021 09:06:49 GMT-0300 (Brasilia Standard Time)] 
[#6688 / 08CCN1WI8P200221] Unhandled notification: /applications/61259cf4cfbcd97059889d12.json 401
  ---  //  ---

**Comment by leomp12** [comment]
É loja demais por causa das lojas da Confere e não deve estar dando tempo
de renovar todos no cron.

Estranho é não ter um retry do paghiper, na segunda tentativa o token
estaria renovado.

Vou ver isso e se for o caso vejo com eles também.

Em qua., 8 de set. de 2021 09:48, Matheus Reis ***@***.***>
escreveu:
