### ISSUE TITLE
Desativar o desconto no meio de pagamento caso haja cupons de desconto aplicados.

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/app-paghiper#3]
Hoje a configuração de desconto acumulativo é feita apenas no CUPOM. Seria importante ter esse processo na forma de pagamento.

Ou seja, caso o cliente estiver utilizando o cupom, o desconto do meio de pagamento seria ‘desativado’.

**Ter opção para desativar o desconto da forma de pagamento caso haja cupom de desconto aplicado.**

![print_fechamento](https://user-images.githubusercontent.com/60987858/90963770-1c098c00-e491-11ea-85f3-be45ec1efe82.jpeg)
Sugestão retirada da [comunidade](https://community.e-com.plus/t/desconto-acumulativo/638/2)

.

**Comment by leomp12** [comment]
@ThaisChaves como é uma alteração na configuração do app é necessário reinstalar ele pra ver a opção de configuração adicionada...
