### ISSUE TITLE
Não consigo instalar paghiper

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/app-paghiper#4]
Desinstalei o app para testar o [issue 3](https://github.com/ecomplus/app-paghiper/issues/3), ao tentar instalar novamente não conclui.

Retorna que não foi possível instalar conforme imagem abaixo:
![paghiper](https://user-images.githubusercontent.com/60987858/93392581-6b9c6700-f847-11ea-9559-8df7325a83b8.png)

Teste feito na loja ID 1117

**Comment by leomp12** [comment]
Oi Thaís,

Vou dar uma olhada nisso, acho que já sei o que é, mas quando for assim
tenta abrir o network e ver a resposta da API por favor, assim fica mais
conclusivo...

Fora isso, não é boa ideia colocar senhas no GitHub

Em qua, 16 de set de 2020 18:09, Thaís Chaves <notifications@github.com>
escreveu:
