### ISSUE TITLE
Problemas com notificação de pagamento aprovado

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-paghiper#8]
Pedidos encontrados a partir do dia 14/12, possivelmente existem outros para trás não tiveram os status atualizados para aprovados.
Por enquanto, relato apenas da loja 1074

**Comment by matheusgnreis** [comment]
@leomp12 olhei http://159.203.20.142/log/nodejs/paghiper.error não consta nada

**Comment by matheusgnreis** [comment]
Exemplo 5fe0c5fb69274c73fceb2109, 5fd7c33169274c73fce8bf38 (mudado manualmente após o cliente reclamar que havia pago)

**Comment by leomp12** [comment]
É só nessa loja e tem vários logs, não está nos erros porque não é um erro da aplicação, a API do PagHiper que está bloqueando as requisições:

```console
ecomplus-integrations [Mon Dec 21 2020 16:50:25 GMT-0200 (Brasilia Summer Time)] 
[#1074 / SAXJ3C1LXT65KM27] Unhandled notification: /transaction/notification/ 401
...
ecomplus-integrations [Tue Dec 22 2020 06:32:55 GMT-0200 (Brasilia Summer Time)] 
[#1074 / 53V5IXHXZBXZS1F3] Unhandled notification: /transaction/notification/ 401
```

Tem vários desse aí, a requisição em `/transaction/notification/` na API do PagHiper não está sendo autorizada, o token pode estar incorreto ou não tem permissão para esse endpoint especificamente.

**Comment by leomp12** [comment]
Nas outras lojas segue normal, vi até um pedido de hoje mesmo já aprovado.

**Comment by matheusgnreis** [comment]
Gera pedido com token invalido?

**Comment by matheusgnreis** [comment]
Testei aqui a credencial dele e de fato, fala q nao está autenticado

**Comment by leomp12** [comment]
> Gera pedido com token invalido?

Sim, só usa esse token na notificação, pra gerar a transação só usa a API key.
